export { AdminByEmail } from './AdminByEmail';
export { UpdatePhone } from './updatePhone';
export { Authorized } from './authorization';
export { Delete } from './delete';
export { AllAdmin } from './AllAdmin';
export { AdminByName } from './AdminByName';
export { UpdatePassword } from './updatepassword';
export { Login } from './login';
export { register, responsefind } from './response';
export { Register } from './register';
export { UpdatePermissions } from './updatePermissions';
export { UpdateEmail } from './updateEmail';
