export { AdminByEmail } from './AdminByEmail';
export { UpadatePhone } from './updatePhone';
export { Authorized } from './authorization';
export { Delete } from './delete';
export { AllAdmin } from './AllAdmin';
export { AdminByName } from './AdminByName';
export { UpadatePassword } from './updatepassword';
export { Login } from './login';
export { register, responsefind } from './response';
export { Register } from './register';
export { UpadatePermissions } from './updatePermissions';
export { UpadateEmail } from './updateEmail';
